### ISSUE TITLE
Build OpenAPI Specification Swagger file(s)

### ISSUE THREAD

**Issue by meteabduraman** [andrei2308/EventManager#3]
Have a **Swagger file** for the API/one for each of the APIs. A Swagger file helps clients that want to use your API to know how to communicate with it and what to expect as responses (it discloses information about the available endpoints, request bodies, response status codes, etc.)

Checkout [this example](https://editor-next.swagger.io/).

Additional links:
- [OpenAPI standard definition](https://swagger.io/specification/)
- [express-openapi](https://www.npmjs.com/package/express-openapi) npm library for automatic creation of Swagger files
- [Swagger Online Editor](https://editor-next.swagger.io/) helping to manually build the Swagger file

This file (or .zip archive of files) then should be uploaded on [online.ase.ro](https://online.ase.ro).

**Comment by meteabduraman** [comment]
@andrei2308 can you add this issue to your Github Project? I think I don't have the permission to do it myself 🤔 You can do it from the sidebar on the right hand-side of this issue

**Comment by andrei2308** [comment]
Salut, sigur, hai ca bag maine la seminar, se rezolva 👍Trimis de pe iPhone‑ul meuPe 21 nov. 2024, la 4:58 p.m., Mete Abduraman ***@***.***> a scris:﻿
@andrei2308 can you add this issue to your Github Project? I think I don't have the permission to do it myself 🤔 You can do it from the sidebar on the right hand-side of this issue

**Comment by andrei2308** [comment]
Done :)
